### ISSUE TITLE
Add database for messages

### ISSUE THREAD

**Issue by lawsonDevvv** [TheRealRaeed/RaeedChat-Feedback#1]
I'd like it if a database was added for messages to be saved (of course, delete messages from the database when they're deleted), allowing support members to be able to view specific messages in reports (along with regular users being able to easily supply message IDs to moderators/admins). Implementation is up to you.

**Comment by TheRealRaeed** [comment]
We do have a logs database, message ids are existent and will be copy able in the next update. Thank you for your suggestion :).

**Comment by lawsonDevvv** [comment]
K.
